### ISSUE TITLE
DOIs Broken?

### ISSUE THREAD

**Issue by colah** [distillpub/template#103]
Distill articles now list DOI for articles with DOIs as "No DOI Yet"

![image](https://user-images.githubusercontent.com/61658/51089237-d5817680-171e-11e9-924e-4b6691ec6ea5.png)

**Comment by ludwigschubert** [comment]
O_o Will fix before next release. Currently unsure what could have caused this.

**Comment by ludwigschubert** [comment]
Fixed in v2.4.1 and deploying atm
