### ISSUE TITLE
Consider using node to serve locally

### ISSUE THREAD

**Issue by rajadain** [distillpub/template#104]
Hello,

I noticed that to serve this static site, currently the template is configured to use Python 3:

https://github.com/distillpub/template/blob/0300b98cb60ff4e28058654acd42459dc1399efc/package.json#L16

Since the app is using npm anyway, it can be made more portable and less dependent on implicit dependencies like Python 3 by using something like [serve](https://www.npmjs.com/package/serve).

If this seems like a worthwhile change, I can make a PR for it.

Thanks.
Terence

**Comment by ludwigschubert** [comment]
Hey, sorry if that caused confusion—I switched to http-server in  94510ee. Thank you! :-)
