### ISSUE TITLE
Latex Formatting

### ISSUE THREAD

**Issue by LK** [distillpub/template#11]
Does the Distill template have any support for typesetting Latex? If not, is there a recommended best practice for doing so?

**Comment by colah** [comment]
Thanks for raising this -- we should update the guide!

Right now, authors have just been using MathJax or KaTeX. In the longer term, we want to render equations server side for faster page loads.

**Comment by dbikel** [comment]
Yes, please include at least _some_ verbiage in the Distill tutorial for best practices for including math in one's publication.  This is such an essential part of publishing a paper in machine learning or computer science that it deserves at least a mention in the tutorial.

**Comment by colah** [comment]
I've added a section about this to the guide.

![image](https://cloud.githubusercontent.com/assets/61658/24225803/c4dfdfdc-0f1f-11e7-89c5-ba33ff28a0ad.png)

**Comment by shancarter** [comment]
I've also added another issue you can follow for a more official solution #21
