### ISSUE TITLE
How are components built?

### ISSUE THREAD

**Issue by chrisgervang** [distillpub/template#12]
Hey there! I've had some fun today reading through the code for most of your articles and template components. I was wondering how you guys are defining the custom DOM elements I see in the template examples (which also on the DOM of the distill website!), such as `dt-article`. 

I use `react` a lot and so I am familiar with the benefit of components, but I was just so surprised to see them in the DOM inspector.

What is the pattern used to build out the components in this template?

Edit: I found how basic articles are [built](http://distill.pub/guide/). I'm still curious about the pattern encouraged for adding visualizations. Is it anything goes at this point?

**Comment by shancarter** [comment]
At this point we don't have a guide for that, but we will soon. The simple story is [html custom elements v1](https://developers.google.com/web/fundamentals/getting-started/primers/customelements).
