### ISSUE TITLE
Copy/pasting the guide produces some NaNs

### ISSUE THREAD

**Issue by j2kun** [distillpub/template#17]
I just copy/pasted the code from the guide (in the interest of reproduction, setting up a [one-click cloneable template](https://github.com/j2kun/distill-template)).

Upon viewing the page, I noticed a few places where some missing data produces `NaN`:

![screen shot 2017-03-22 at 10 53 34 am](https://cloud.githubusercontent.com/assets/2467754/24212903/06b0fdb0-0eee-11e7-9acd-6234e42db39b.png)

```
. NaN
NaN
```

And 

```
Citation: 
Olah & Carter, NaN
```

![screen shot 2017-03-22 at 10 58 43 am](https://cloud.githubusercontent.com/assets/2467754/24213071/8dc65570-0eee-11e7-93bc-ce6e440dca97.png)

```
, NaN.
```

![screen shot 2017-03-22 at 10 53 38 am](https://cloud.githubusercontent.com/assets/2467754/24212924/144028a2-0eee-11e7-9b00-6b1ecddd96c7.png)

```
@article{olahNaNarticle,
```

and

```
year = {NaN}
```

**Comment by j2kun** [comment]
It seems like there's a missing "year" number, but no clear indication of where to put it to make it render.

**Comment by j2kun** [comment]
Also, `create an issue on GitHub.` link has `undefined` as the repo, as does the `source available` link. Amusingly, it send you to a real page: https://github.com/undefined

**Comment by shancarter** [comment]
I've removed those sections for now from non-distill articles.
