### ISSUE TITLE
Bibtex entries ignored when fields are capitalised

### ISSUE THREAD

**Issue by shakirm** [distillpub/template#20]
Via @mpd37
Bibtex entries are not case sensitive with respect to the fields in the bibtex entry. For example, there is no difference in latex between using:

% Capitalised field names
@article{rasmussen2006gaussian,
  Title={Gaussian processes for machine learning},
  Author={Rasmussen, Carl Edward},
  Year={2006},
  Publisher={Citeseer}
}

% Lowercase field names
@article{rasmussen2006gaussian,
  title={Gaussian processes for machine learning},
  author={Rasmussen, Carl Edward},
  year={2006},
  publisher={Citeseer}
}

The current distill template ignores bibtex entries formatted in the first way (with capitalised fields, as might be generated when using a referencing tool like Jabref), and includes them for the second way. Could we make a note of this or make it non-case sensitive.

**Comment by colah** [comment]
Thanks for catching this! I believe I've found the problem and should have it resolved shortly.

**Comment by colah** [comment]
Fixed!
