### ISSUE TITLE
Scope of distill

### ISSUE THREAD

**Issue by EndingCredits** [distillpub/template#22]
Sorry if this is the wrong place to ask, since this isn't a technical question but rather a more general question about the platform.

I appreciate this may still be something of an unknown, but I was wondering what sort of non-traditional content distill will be considering.

Broadly speaking I can think a number of different types of potentially valuable content (split into the following, slightly arbitrary, categories):
- Original research: Publishable research which benefits from the extra flexibility of the distill platform.
- Visualisations and artifacts: Tools which may be useful for other researchers, but aren't really suitable for publication via traditional academic media.
- In-depth analysis of a particular area: Theoretical and/or empirical analysis of a given area (perhaps supported by visualisations) where the novel contribution may not be directly publishable (eg suggesting a new paradigm or idea which may not be fully fleshed out yet, or have been tested in an experimental setting). [This post by Chris](http://colah.github.io/posts/2014-12-Groups-Convolution/) might be an example of this.
- Exposition of a particular area: Similar to the previous case, but where the intention is raise awareness of, and educate on, an existing field/idea, rather than present a new idea of the author. For example, [Karpathy's post on RNNs](http://karpathy.github.io/2015/05/21/rnn-effectiveness/).
- Tutorial: A crash course on some new technique.
- Personal notes: Formatted notes, perhaps including detailed explanations of particular experiments ([including failures](http://negative.vision/)).

I expect that not all of these would be suitable for distill (although personally I think they all deserve their own outlet somewhere), so it would be good to hear the editors' (and the wider community's) thoughts.

**Comment by colah** [comment]
Thanks for raising this! Sorry it fell through the cracks.

We recently updated our [journal policies page](http://distill.pub/journal/), but there's still a lot more for us to clarify.
