### ISSUE TITLE
Include file/link in code block

### ISSUE THREAD

**Issue by frsong** [distillpub/template#25]
Is it possible to include selected lines from a file or link in a code block? It would also be nice to be able to highlight parts of the included code.

**Comment by shancarter** [comment]
Can you clarify a bit, I don't follow.

**Comment by frsong** [comment]
In LaTeX, for example, I can include code using either

\begin{lstlisting}
x = 3
\end{ltslisting}

or 

\lstinputlisting[linerange={3-5}]{code.py}

It's also possible to highlight certain lines. I think all of these capabilities are really useful when including code in a tutorial, so that instead of copy-pasting we can include code directly from a file that can also be run (and tested). It would be even better if we could include code from a GitHub repo.

Maybe this can already be done, but I didn't see it in the documentation. Thanks!

**Comment by colah** [comment]
We do not presently support this. I think it's an interesting idea -- especially ways of integrating with github -- but we are unlikely to add it in the near future.

One challenge is that referencing external files like this runs into issues with browser security policies. To use these features, authors would need to do an extra step like run a local server. This is kind of a pain. :/ I expect we'll bight that pill at some point, but so far we've avoided it.

**Comment by j2kun** [comment]
Adding code snippets should be straightforward. If, as it seems, this is not a high priority request, I could chip away at it in my spare time.

Then again, what is the use case for including code listings in an ostensibly mathematical insights paper?

**Comment by colah** [comment]
To be clear, Distill does support code blocks:

```html
<dt-code block language="javascript">
  var x = 25;
  function(x){
    return x * x;
  }
</dt-code>
```

frsong has suggested we support code from files or github. That's an interesting ideas, but raises some broader issues.
