### ISSUE TITLE
Using colons in title field of frontmatter

### ISSUE THREAD

**Issue by shakirm** [distillpub/template#29]
Using a colon in the title field (or other fields) of the frontmatter breaks page rendering: the citations do not appear, and the yellow bar indicating draft mode does not appear. This can be fixed, by including frontmatter fields within quotations. Might be useful to point this out somewhere.

**Comment by colah** [comment]
Thanks for raising this, Shakir!

... Maybe we should just write our own parser? This seems kind of silly. Isn't the parser 40K to parse those couple of lines?

**Comment by shakirm** [comment]
An easy initial fix is to write the initial template that is supplied with the quotation marks. Everyone will assume that this is how it should be done and will avoid needing to provide extra instruction anywhere else. Maybe later the parser can be looked at in more depth - depending on how that interacts with other aspects of the template.

**Comment by colah** [comment]
Updated the guide to add quotes.

I'll keep this issue open in case we want to do a more thorough solution.

**Comment by ludwigschubert** [comment]
V2 uses JSON for frontmatter, which doesn't need a parser in most environments we care about, and handles colons. I'll close this for now.
