### ISSUE TITLE
Table formatting

### ISSUE THREAD

**Issue by jppgks** [distillpub/template#36]
```html
<!doctype html>
<meta charset="utf-8">
<script src="http://distill.pub/template.v1.js"></script>

<dt-article>
  <p>
    This paragraph displays the correct alignment.
    The table element should follow layout rules and have styling.
  </p>
  <table>
    <tr>
      <th>Column</th>
    <tr>
    <tr>
      <td>Entry</td>
    </tr>
  </table>
</dt-article>
```

Output:
![Table example](http://i.imgur.com/XKQieg9.png)

**Comment by shancarter** [comment]
Added some basic styles for tables. https://github.com/distillpub/template/commit/afc798f7a062726f1009a509f277c83c9070e307

![image](https://cloud.githubusercontent.com/assets/418356/25100457/01abd3cc-2365-11e7-9e52-6be5fccd167e.png)
