### ISSUE TITLE
Whitespace Inconsistencies in Build

### ISSUE THREAD

**Issue by colah** [distillpub/template#37]
In PR #35, we found that the build process is producing different whitespace for different people. This leads to extra stuff in the diffs like:

![image](https://cloud.githubusercontent.com/assets/61658/25097303/ded3a19c-2358-11e7-970c-d8da2ae69a8d.png)

It would be nice to figure out what's going on and fix it.

**Comment by shancarter** [comment]
It's possible there are two different versions of a third-party library being compiled in.

**Comment by jppgks** [comment]
What version of `yarn` are you guys on? I'm at `0.23.2`.

**Comment by ludwigschubert** [comment]
Closing as we no longer check in build results. Please reopen if this is still an ongoing issue for PRs!
