### ISSUE TITLE
dt-code block support for python

### ISSUE THREAD

**Issue by kedartatwawadi** [distillpub/template#42]
Hello! Thanks for providing the template.
What all languages are supported by dt-code for syntax highlighting? I tried python, but it did not seem to work. 
```python
<dt-code block language="python">
    class BinaryNode:
    	def __init__(self,_id):
    		self.left = None
    		self.right = None
    		self.id = _id
    		self.num_phrases = [0](`url`)
  </dt-code>
```

Can you point me out to the place where I should make changes to add this functionality?

**Comment by colah** [comment]
You want to look at [components/code.js](https://github.com/distillpub/template/blob/master/components/code.js). The relevant lines are:

```javascript
    let highlighted = content;
    if (Prism.languages[language]) {
      c.setAttribute("class", "language-" + language);
      highlighted = Prism.highlight(content, Prism.languages[language]);
    }
```

Python is on the list of [supported languages](http://prismjs.com/#languages-list) (as `python`) as are many others. But it turns out that `Prism.languages` only has these keys:

```javascript
> Object.keys(prism.languages)
[ 'extend', 'insertBefore',  'DFS', 'markup',  'xml', html', 'mathml', 'svg', 'css', 'clike', 'javascript',  'js' ]
```

I guess one needs to do something to include more languages?

**Comment by ludwigschubert** [comment]
You are right, those are the _default_ languages that `Prism.js` ships with (see[ their download page](http://prismjs.com/download.html)). We could:

- switch to a version with a couple more common languages included (maybe python and clike), or
- think about a way to parametrize that at build time if we really need to; they offer a parametrized download URL via query parameters, e.g. `http://prismjs.com/downloaad.html?themes=prism&languages=markup+css+clike+javascript+python`

**Comment by colah** [comment]
Thanks for looking into this, Ludwig! :)

@shancarter, going to defer to you on how to deal with this... My inclination is is to look through the doc, pull out the languages for dt-code, and grab those. Maybe ship a larger set of common languages?

**Comment by shancarter** [comment]
We should just ship all the useful languages, if I recall this code gets compiled out on publish anyway.

**Comment by shancarter** [comment]
Python and several other languages added #43

**Comment by kedartatwawadi** [comment]
Hi all, Thanks a lot for taking a look at the issue! (apologies for the late reply)

**Comment by colah** [comment]
You're very welcome, Kedar - thanks for pointing it out!
