### ISSUE TITLE
Tutorial for diagrams

### ISSUE THREAD

**Issue by botcs** [distillpub/template#44]
Could you please extend the _Diagrams_ section on the How to page?

To be a bit more specific, I would like to know for example how interactive diagrams were not just coded, but designed in previous articles.

**Comment by ludwigschubert** [comment]
Entirely agree! We are planning to have more in depth-tutorials and a description of how we think about writing and designing Distill articles in the future. I can't guarantee any dates or even fully commit to it, but I can tell you that we are actively considering it. ;-)
