### ISSUE TITLE
Rename events

### ISSUE THREAD

**Issue by shancarter** [distillpub/template#51]
https://github.com/distillpub/template/blob/08fafcf2ee03839ffb7b27b1450b9713ab147d72/src/components/d-figure.js#L9

We should simplify these events. 

ready -> onscreen -> offscreen

are probably all we need. Ready will only ever fire once, for use when the figure is first close to or is in view, for loading resources and initializing code.

**Comment by ludwigschubert** [comment]
Agreed and implemented in https://github.com/distillpub/template/commit/9993a679c1b4481dc25c580dd3e20bbf5eed9289 !
