### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by siarez** [distillpub/template#60]
I just found out about this project, got very excited, but then realized there has been very little activity. What is the status?

**Comment by colah** [comment]
Yep, there are a number of articles in the works. :)

**Comment by siarez** [comment]
Oh great! Just to clarify, it is possible to use this framework on your own website even if you don't intend on publishing on distill.pub?
(I just realized you are the person behind http://colah.github.io, I really enjoyed your “Visual Information Theory” post :)  )

**Comment by shancarter** [comment]
Unfortunately we don't currently provide a license for this code but we hope to update that with a future release.
