### ISSUE TITLE
Add KATEX to Markdown editing

### ISSUE THREAD

**Issue by ofou** [distillpub/template#61]
In `template/examples/tutorial.html` you didn't specify how you should use Markdown in conjunction with KATEX, is possible to do that? I tried it but with no success. 
It would be a great add on to the project for example using [markdown-it](https://github.com/waylonflinn/markdown-it-katex)! and adding `$f(x)$` to render inline and `$$f(x)$$` to render as a block.

**Comment by ludwigschubert** [comment]
Since most people needed a lot more customization than easily possible in markdown, we don't currently have robust, documented support for it. We hope to bring it back in the future; stay tuned!
