### ISSUE TITLE
Add DOI to bibtex citation

### ISSUE THREAD

**Issue by shancarter** [distillpub/template#62]
A comment from hacker news: 
https://news.ycombinator.com/item?id=15648422

JorgeGT 1 hour ago [-]
Minor note, you should add the field DOI={10.23915/distill.00007} to the BibTeX citation. This is also missing from Google scholar, and is a particular pat peeve of mine now that DOIs are practically mandatory (copying the helpfully-formatted citation but then having to look around the page to find the DOI).
--

**Comment by ludwigschubert** [comment]
Fixed in 315e8888!
