### ISSUE TITLE
Using Framework Externally

### ISSUE THREAD

**Issue by Scikud** [distillpub/template#65]
Hi, I really love the style and look of the distill framework, I was wondering if it was possible to use it without intending on publishing an article on Distill? If so, how would I go about this? Thanks so much.

**Comment by ludwigschubert** [comment]
While we're happy for you to use the Distill styling, I'm afraid we don't have the resources to help you with that request in detail. 

(You could consider looking at [Arxiv Vanity](https://www.arxiv-vanity.com/), which uses some Distill styling.)
