### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by BigBlueHat** [distillpub/template#69]
First, thanks for building this project! I just found this via the fabulous https://github.com/arxiv-vanity/engrafo project.

Second, is this project meant to be open source? If so, it will need a license in order to "flip the default" from "All Rights Reserved." See https://oss.kemitchell.com/#defaults-and-overrides for more info.

http://choosealicense.org/ has more help for picking a license to fit your needs (if you even need it). 😄 

Thanks!
🎩

**Comment by jbenet** [comment]
We'd like to be able to use some of the styling from distill (it's beautiful). 

License is really unclear. the posts are licensed MIT and may contain some of that styling (css), so technically can argue it's MIT-ed, but could also claim it originates in this repo which _does not_ have a license.

Please add an MIT license here, or a license that you feel sure about so we know. 

If there are some files that are IP-tricky, then maybe add a license for those files that are fine (header of files, or move the offending files out of this repo for now).

thanks for attention to this

**Comment by bofinbabu** [comment]
Yes please be clear about your intentions about how this project should be licensed. Thanks

**Comment by ludwigschubert** [comment]
It took a while, but we are happy to report that `distillpub/template` is now licensed under the Apache 2.0 license.

FYI, @jbenet all Distill _posts_ themselves are CC-BY licensed, as is stated on each post.

![image](https://user-images.githubusercontent.com/1167977/38150636-ca8935b2-3414-11e8-88c4-598b0a3f70ed.png)
