### ISSUE TITLE
Article Layout

### ISSUE THREAD

**Issue by shancarter** [distillpub/template#7]
We're exploring some ideas around the layout of a `dt-article`.

Some motivations:

- Signal visually that these are not just blog posts. Often times the articles contain a huge amount of content and depth, which is somewhat hard to understand at first glance.

- Signal that we are archiving and indexing these articles with libraries and generally being a good `academic` citizen.

- Provide best practices for common conventions and guidance for overcoming common frustrations around making the first load experience visually compelling. Examples: hero interactives, summary illustration, collage/summary of elements to come?

- There are some general features we'd like to add as well, sharing prompt, TOC linking, etc...

Present Design
===========

As a frame of reference, here are some representative examples of the current design:

**[Click to enlarge images]**

Text | Hero
-- | --
![image](https://cloud.githubusercontent.com/assets/418356/22947219/097f9408-f2af-11e6-9b58-839fbcf7e0ae.png) | ![image](https://cloud.githubusercontent.com/assets/418356/22947246/29948230-f2af-11e6-8f0d-d7365898a2e0.png)

Content stripes
===========

Each stripe would be optional, except the headline. The abstract/TOC would only be included on especially long posts. Possible to do a "visual" TOC too maybe?

**[Click to enlarge images]**

Text | Hero | Headline and byline together
-- | -- | --
![image](https://cloud.githubusercontent.com/assets/418356/22954575/1f622f3e-f2cc-11e6-8e1d-bf833e5272c7.png) | ![image](https://cloud.githubusercontent.com/assets/418356/22954586/2ee214ba-f2cc-11e6-94bf-6c28be1eeefa.png) | ![image](https://cloud.githubusercontent.com/assets/418356/22954623/5208bf7a-f2cc-11e6-9d16-6d810e882a59.png)

Dark Header
==========

**[Click to enlarge images]**

Text only | With a Hero
------------ | -------------
![image](https://cloud.githubusercontent.com/assets/418356/22954636/76fddec8-f2cc-11e6-98c5-e596ad94cab3.png) | ![image](https://cloud.githubusercontent.com/assets/418356/22954646/8b6820da-f2cc-11e6-9069-a70c6af6623d.png)

Dark blue brought down to author bar
============================

**[Click to enlarge images]**

Text | Hero | Hero full bleed
-- | -- | --
![image](https://cloud.githubusercontent.com/assets/418356/22956489/30c333da-f2d7-11e6-9b46-c853d4a82c41.png) | ![image](https://cloud.githubusercontent.com/assets/418356/22956485/29d70e98-f2d7-11e6-9e48-b7c13fa8edef.png) | ![image](https://cloud.githubusercontent.com/assets/418356/22956516/74cf8c22-f2d7-11e6-805a-006772942427.png)

Total White Top
============

Text | Hero
-- | --
![image](https://cloud.githubusercontent.com/assets/418356/23001385/df61f8be-f399-11e6-8595-6cea6042853b.png) | ![image](https://cloud.githubusercontent.com/assets/418356/23001377/ce3180fa-f399-11e6-84a6-dc0db5ce4b57.png)

**Comment by shancarter** [comment]
![image](https://cloud.githubusercontent.com/assets/418356/22954575/1f622f3e-f2cc-11e6-8e1d-bf833e5272c7.png)


![image](https://cloud.githubusercontent.com/assets/418356/22954586/2ee214ba-f2cc-11e6-94bf-6c28be1eeefa.png)

**Comment by shancarter** [comment]
![image](https://cloud.githubusercontent.com/assets/418356/22954636/76fddec8-f2cc-11e6-98c5-e596ad94cab3.png)

![image](https://cloud.githubusercontent.com/assets/418356/22954646/8b6820da-f2cc-11e6-9069-a70c6af6623d.png)

**Comment by shancarter** [comment]
There's also been some discussion of a visual table of contents, some extension of what we did on the first article:

![image](https://cloud.githubusercontent.com/assets/418356/22955069/136537e6-f2cf-11e6-9c27-eb49313066b8.png)

**Comment by shancarter** [comment]
Dark blue brought down to author bar:

![image](https://cloud.githubusercontent.com/assets/418356/22956485/29d70e98-f2d7-11e6-9e48-b7c13fa8edef.png)

![image](https://cloud.githubusercontent.com/assets/418356/22956489/30c333da-f2d7-11e6-9b46-c853d4a82c41.png)

![image](https://cloud.githubusercontent.com/assets/418356/22956516/74cf8c22-f2d7-11e6-805a-006772942427.png)

**Comment by shancarter** [comment]
We would like to have a "title page" or "cover" for the articles that communicates:

- An overview of what is contained inside

- This article is more substantial than a typical blog post. 

- Make it look interesting without people assuming that the cover is the entire article.

- Not be too visually chaotic. Like a good cover to a book.

- Interesting without feeling reductive, repetitive or gratuitous.

In some ways these articles are moving against the grain of the web. The more the hero or title page is interesting content and self contained, the more it because a full-fledged atomic unit of the web. The natural state of the web is short, bite-sized pieces. The web is infinitely plastic, but every medium has a natural state.

How much should we mold the content to the natural state of the web? How much should we swim along with this current? How do we best communicate complicated, deep ideas in a medium whose natural state is short, self-contained snippets?

**Comment by shancarter** [comment]
**Secondary Headlines**

Allowing subheads in the dark header area feels too visually complicated. Would be nice if we could get away with never having a deck in the main header, but it's made tough by having a hero interactive that you want to introduce. We could possibly just force the hero interactive to introduce itself with a caption somewhere.

Text | Hero
-- | --
![image](https://cloud.githubusercontent.com/assets/418356/22999893/b61ec650-f392-11e6-97aa-afffaafb46b0.png) | ![image](https://cloud.githubusercontent.com/assets/418356/22999907/c4338fe6-f392-11e6-8b42-7e2a8feb3983.png)

**Comment by shancarter** [comment]
## Metadata on the side

Text | Hero
-- | --
![image](https://cloud.githubusercontent.com/assets/418356/23034969/7e0e0e24-f432-11e6-8384-b3fff3ac69c7.png) | ![image](https://cloud.githubusercontent.com/assets/418356/23034979/854b099e-f432-11e6-993b-093bc5be5194.png)

**Comment by jppgks** [comment]
👍 for dark header with light bar.
👍 for metadata in bar.

**Comment by shancarter** [comment]
<img width="612" alt="screen shot 2017-03-23 at 2 46 12 pm" src="https://user-images.githubusercontent.com/418356/27715360-696502ee-5ceb-11e7-8e17-c1202773001f.png">

![screen shot 2017-03-10 at 4 14 03 pm](https://user-images.githubusercontent.com/418356/27715359-695f5bb4-5ceb-11e7-9622-3ef82d00fafd.png)

**Comment by ludwigschubert** [comment]
Closing this for V2; let's make a new issue with plans for further enhancements as we plan them!
