### ISSUE TITLE
Does the template support writing in markdown?

### ISSUE THREAD

**Issue by xu-song** [distillpub/template#75]
The theme of distill  is fancy.  We can not generate such fancy page via pure markdown. 
Maybe `html_tag enhanced markdown` can do it.
It would be helpful if there is a `markdown template` for this theme,

**Comment by ludwigschubert** [comment]
It does not at the moment—as you correctly note, most Distill articles use much more customization than markdown could easily provide. We do see, though, that there may be demand for a simpler authoring experience, and are keeping this in mind for future development.

**Comment by stared** [comment]
@ludwigschubert  Did anything changed on that matter?

Or alternatively - is it possible to use [Distill for R Markdown](https://rstudio.github.io/distill/) for submission?
