### ISSUE TITLE
Figure Shell

### ISSUE THREAD

**Issue by shancarter** [distillpub/template#9]
Might be useful to have a `dt-figure` element that handles a few things:

- Loading of large datasets with a loading indicator.

- Defer computation for down-page figures so we don't pummel the browser with computation and loading on pageload. As you scroll, get updates when you're about to be onscreen, when you're onscreen and when you're offscreen.

**Comment by ludwigschubert** [comment]
`<d-figure>` covers most of this; closing for now—but will keep in mind for further development; especially the asset loader.
