### ISSUE TITLE
In-line math floating above baseline

### ISSUE THREAD

**Issue by greydanus** [distillpub/template#96]
Hi,
I'm having some trouble rendering the inline katex in Distill articles. My current browser info is below.

![image](https://user-images.githubusercontent.com/18602382/49820852-e0b34200-fd2d-11e8-9f4e-436f3fe7bb0b.png)

Google Chrome | 71.0.3578.80 (Official Build) (64-bit)
-- | --
Revision | 2ac50e7249fbd55e6f517a28131605c9fb9fe897-refs/branch-heads/3578@{#860}
OS | Mac OS X
JavaScript | V8 7.1.302.28
Flash | 32.0.0.101 /Users/sgrey/Library/Application Support/Google/Chrome/PepperFlash/32.0.0.101/PepperFlashPlayer.plugin
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36

**Comment by ludwigschubert** [comment]
Is this still the case? Can not reproduce in Chrome 70, or any major browser. Trying Chrome 71 now…

![image](https://user-images.githubusercontent.com/1167977/50115602-badddf80-01fc-11e9-92ff-196e4a53ce28.png)

![image](https://user-images.githubusercontent.com/1167977/50115616-c3ceb100-01fc-11e9-925d-7b8a25c1e386.png)

![image](https://user-images.githubusercontent.com/1167977/50115627-cd581900-01fc-11e9-934a-8d9c899fc36f.png)

**Comment by ludwigschubert** [comment]
Can reproduce, but in Chrome 71 only. Investigating…

**Comment by greydanus** [comment]
Seems to be working for me now too. Thanks Ludwig!
