### ISSUE TITLE
Custom katex delimiters don't render in appendices

### ISSUE THREAD

**Issue by girving** [distillpub/template#97]
In `renderMathInElement` is called only on `d-article` due to https://github.com/distillpub/template/blob/master/src/transforms/mathematics.js#L20.  In particular, stuff in `d-appendix` isn't processed.

**Comment by ludwigschubert** [comment]
Jupp, good find—this operated on an old assumption that all important content is under `d-article`.

**Comment by girving** [comment]
Thank you!
